hypercerts-org/hypercerts

frontend/components/contract-interaction-dialog-context.tsx
frontend/components/hypercert-create.tsx

* Added text in the dialog to ask user to not close the tab while minting
* For some reason the page was reloading when I submitted the create form. Fixed via e.preventDefault
* Printing some debug messages around the create form
* Includes Plasmic updates
* Properly parameterize the GraphQL query to load my tokens (previously hardcoded address)

fix(create): Fix create to dashboard

---

frontend/plasmic-init.ts

* What does this mean? Builds will only pull the latest published version.
* Previously builds would pull the latest from Studio, regardless of whether it was published or not --- good for rapid development but terrible for stability
* If you are making changes to Plasmic and *no* code changes, nothing changes about your workflow.
* If you are making changes to code and not Plasmic, nothing changes either.
* If you are a developer making simultaneous changes to Plasmic and code components, you now have to remember to publish a Plasmic version before pushing your code to a PR.

fix: Disable preview mode in Plasmic

---

frontend/components/forms.tsx
frontend/components/hypercert-create.tsx
frontend/plasmic-init.ts

* Add a disabled option to DatePickers
* Remove the impactTimeStart from the form. Just reuse workTimeStart as per https://github.com/Network-Goods/hypercerts/issues/169

fix: hypercert create form

---

frontend/components/hypercert-create.tsx

* Previously we had a useless `fractions` field in the form data, which would sometimes show up in our URLs --- removed this.
* mintClaim is adjusted to always mint 10000 units
* mintClaimAllowlist unchanged --- just sums up the units from the allowlist to be the totalSupply

fix: remove fractions from the form

---

frontend/components/forms.tsx
frontend/components/hypercert-create.tsx

* Adds an error label when we're in indefinite date. It was previously hidden with the textfield
* Change the validation logic to allow for mixed types string or Date for impactTimeEnd.

fix: impactTimeEnd  validation in create form

---

frontend/components/hypercert-create.tsx
frontend/lib/parsing.ts

contributors
* Does case-insensitive duplication checks
* Added new options to a parseStringToList utility function

fix: Add form validation logic to error out on duplicate workScopes or

---

frontend/hooks/mintClaimAllowlist.ts
frontend/lib/parsing.ts

* previously we didn't trim every element in the CSV parsing. That led to things like 'fractions \r' or '100.0 '
* Trimming will clean this right up!

fix: CSV parsing needs more trimming

---

frontend/components/claim-all-fractions-button.tsx
frontend/components/connect-wallet.tsx
frontend/components/dapp-context.tsx
frontend/components/hypercert-create.tsx
frontend/hooks/account.ts
frontend/hooks/mintClaimAllowlist.ts
frontend/hooks/mintFractionAllowlistBatch.ts

* This has been messing with us since day 1. useAccount returns back addresses that are a mix of upper and lower case.
* Added a new useAccountLowerCase that will lowercase the address.
* Plumb this everywhere so that we're always using lowercase addresses

fix: lowercase addresses

---

frontend/components/claim-all-fractions-button.tsx

success
* The timeout should not affect failed claim attempts.
* Previously after success, it would still show as clickable because it takes time to propagate from Ethereum => Defender => Supabase. If a user clicks at that point, it would fail because we just claimed

fix: adds a 5 minute timeout to the claim all fractions button after

---

contracts/src/HypercertMinter.sol
contracts/test/foundry/HypercertMinter.batchminting.t.sol
contracts/test/foundry/HypercertMinter.t.sol

* Previously, if the token restriction was set to DisallowAll or FromCreatorOnly, creating from an allowlist led to failures

fix: transfer restrictions don't apply to minting or burning

---

.lintstagedrc
README.md
sdk/.env.template
sdk/README.md
sdk/package.json
sdk/src/.graphclient/index.ts
sdk/src/.graphclient/schema.graphql
sdk/src/.graphclient/sources/hypercerts-dev/introspectionSchema.ts
sdk/src/.graphclient/sources/hypercerts-dev/schema.graphql
sdk/src/.graphclient/sources/hypercerts-dev/types.ts
sdk/src/errors.ts
sdk/src/index.ts
sdk/src/operator/index.ts
sdk/test/interface.test.ts
sdk/test/operator.test.ts
sdk/yarn.lock

* Added web3.storage support, swapped in for `storeData` and `getData`.
* Run `yarn build`, which replaced files in `.graphclient/`
* Removed `deleteMetadata`. Not sure this is an operation we want people to do
* Ignoring sdk for lint-staged at the moment, until we can get it actually integrated into the turbo monorepo build
* Added typed errors to SDK

feat: Add support for web3.storage

---

sdk/.env.template
sdk/.graphclientrc.yml
sdk/src/index.ts
sdk/src/operator/hypercerts-storage.ts
sdk/src/operator/index.ts

* This allows us to pass in NFT.storage and web3.storage keys into a Storage class so that we don't have to rely on implicit environment variables
* Remove GRAPH_URL from .env, I don't think we're using it
* Updated the hardcoded graph URL endpoint in the codegen

feat(sdk): Add a HypercertsStorage class

---

defender/src/auto-tasks/batch-mint-claims-from-allowlists.ts
defender/src/auto-tasks/mint-claim-from-allowlist.ts
defender/src/auto-tasks/on-allowlist-created.ts
defender/src/config.ts
defender/src/create-autotask.ts
defender/src/create-sentinel.ts
defender/src/errors.ts
defender/src/networks.ts
defender/src/reset.ts
defender/src/setup.ts
defender/tsconfig.json

* Added custom error types
* Added network configuration in `defender/src/networks.ts`
* Abstract out the reset code into a separate file `reset.ts`
* Encode the network name in the autotask name, and use that to retrieve configurations
* Created a config wrapper
* Run through the setup script for each network defined in config
* Changed module resolution to `node` so that webpack can load utility functions

fix: update defender scripts to support multiple networks

---

defender/package.json
defender/src/HypercertMinterABI.ts
defender/src/auto-tasks/batch-mint-claims-from-allowlists.ts
defender/src/auto-tasks/mint-claim-from-allowlist.ts
defender/src/auto-tasks/on-allowlist-created.ts
defender/src/create-sentinel.ts
defender/src/errors.ts
defender/src/networks.ts
defender/src/setup.ts
docs/docs/devops/deploy-proxy.md
yarn.lock

* Hardcode the HypercertMinterABI into defender due to autotask restricted environment
* Remove all dependencies on @hypercerts-org/* packages
* Better logging and data validation for debugging
* Use Alchemy provider for retrieving transaction data
* Get AllowlistCreated events from Alchemy. Not sure what happened but event.request.body.matchReasons are no longer being populated from OpenZeppelin
* More info on devops playbook

fix: Defender scripts

---

sdk/docs/RELEASE.md
sdk/package.json
sdk/src/operator/index.ts
sdk/test/operator.test.ts

* wrapDirectory is default behavior, which wraps the file in a directory
* What we want is just to get the item we stored at the root

fix(sdk): getData in SDK should NOT wrapDirectory

---

frontend/components/claim-all-fractions-button.tsx
frontend/components/config.tsx
frontend/components/dapp-context.tsx
frontend/lib/verify-fraction-claim.ts
frontend/plasmic-init.ts
sdk/src/operator/index.ts

* Adding a Config code component that exposes app configuration
* Expose whether we claimed recently to DappContext
* Removed the hardcoded disable in ClaimAllFractionsButton and added a disabled toggle (that can be controlled via Plasmic)
* Added some in-line commentary about why `getData` is failing in the frontend

fix: add config component to Plasmic

---

contracts/.openzeppelin/goerli.json
contracts/src/SemiFungible1155.sol

* We only store the URI on the base type, so getting URI was failing on any tokenIDs.

fix: uri broken in contract

---

defender/package.json
defender/src/create-sentinel.ts
defender/src/setup.ts
yarn.lock

* Removed extra layer of JSON.stringify, which double quoted our ABI and kept the Sentinel client from properly parsing the ABI
* This led to event/function triggers not being set up properly, so the default behavior is to trigger on anything, causing failures
* Bumped client versions for defender libraries
* Simplified names

fix: Defender not triggering on right events

---

frontend/components/forms.tsx
frontend/components/hypercert-create.tsx
frontend/plasmic-init.ts

* When using MUI checkboxes with formik, the visual checked state was inconsistent with the form state. For example, if you set default initial value to true, it won't show true. This lead to a number of bugs where the checkbox was actually checked/unchecked when we didn't expect it to.
* Reverting to using the default checkbox in formik for now to avoid these issues

fix: fix inconsistent checkbox visual state

---

frontend/hooks/mintClaimAllowlist.ts
frontend/jest.config.js
frontend/jest.setup.js
frontend/lib/errors.ts
frontend/lib/parsing.test.ts
frontend/lib/parsing.ts
frontend/package.json
yarn.lock

* Added an allowlist CSV parsing utility function, with the ability to combine duplicates, and manually add entries to a CSV
* Added jest to the frontend, with tests for the allowlist parsing
* Replace manual CSV parsing with papaparse
* Added some validation error types
NOTE: this hardcodes 50% of the total supply to the minter

feat(allowlist): Add more sophisticated allowlist management

---

frontend/components/contract-interaction-dialog-context.tsx

* Just shows up for the active step. Helps the user feel less anxious about waiting

fix: add a simple indefinite progress bar in contract modal

---

sdk/.graphclient/index.ts
sdk/RELEASE.md
sdk/package.json
sdk/src/queries/fractions.graphql
sdk/src/resources/schema/metadata.json
sdk/src/utils/formatter.ts
sdk/test/formatter.test.ts

Fix for #528 
OpenSea doesn't handle empty `properties[]` and/or `external_url`. 
* Made these fields optional in the schema
* Regenerated types 
* Only add these field to metadata when they are not undefined/empty
* Added tests to SDK
* Successful [test mint](https://testnets.opensea.io/assets/goerli/0x822f17a9a5eecfd66dbaff7946a8071c265d1d07/113314028184672508333303744274778814414849
)
Fix for #540 
Not all fractions owner by a user are displayer in the front-end
* Removed arbitary 30-limit from fractions query
TODO

Handle undefined/empty values in metadata formatting

---

.github/workflows/ci-default.yml
frontend/components/hypercert-fetcher.tsx

* Currently we are only using window.location.search, which gets all messed up on Fleek for some reason. Adding the option to accept query strings via hash parameters in HypercertFetcher

fix: accept querystrings via window.location.hash in hypercertfetcher

---

frontend/next.config.js
frontend/package.json
package.json
turbo.json

* Fixing next.config.js, which was overwriting module.exports
* Add manual sourcemaps upload commands to package.json
* Uses `propose-version` to get the commit hash for release versioning

fix: Sentry sourcemaps

---

frontend/components/hypercert-create.tsx
frontend/hooks/mintClaimAllowlist.ts
frontend/hooks/mintClaimAllowlistSDK.ts
frontend/lib/parsing.ts
sdk/src/index.ts
sdk/src/validator/index.ts

* Refactored `hypercerts-create.tsx` to use SDK method
* Exposed Allowlist types via SDK
* Updated allowlist validation/parser
* Added throw on CSV parse error. The warning was blocking so upgraded it to error
* Updated allowlist validator equal checks
Works on #513

feat(sdk): createAllowlist using SDK

---

.github/workflows/ci-default.yml
package.json
turbo.json

* Need to hash cached output based on Plasmic env variables
* dist/ needs to be cached
* Removing extraneous workspace-specific config that isn't actually used

fix: turbo caching

---

sdk/src/operator/hypercerts-storage.ts

* Currently we are using the NFT storage gateway, even for retrievals from web3.storage. Replacing the gateway used to w3link for web3.storage retrievals

fix: use w3link for retrieving from web3.storage

---

frontend/package.json
package.json
sdk/package.json
turbo.json

* yarn deploy:site is kept as a static export for Fleek and Cloudflare
* Vercel will use yarn build:frontend to deploy a full Next.js application

fix: Vercel build should not use `next export`

---

frontend/next.config.js

* These trigger a warning that they're not valid properties in the config

fix: remove `settings` and `rules` from next.config.js

---

os-observer/src/events/npm.ts
os-observer/src/utils/parsing.ts
os-observer/test/parsing.test.ts

* want to be able to extract both the owner and name from a URL
* updated unit tests to reflect that

feat: refactor getGithubOrgFromUrl to parseGitHubUrl

---

os-observer/src/events/npm.ts
os-observer/src/utils/common.ts
os-observer/src/utils/error.ts

* Default fetch npm downloads since the beginning of npm
* Add validation logic for basic types
* Add recursion to keep fetching daily downloads into the past if we get
incomplete results. Assumes that NPM will always return the newest
dates before older dates.
* Fix bug where date comparison should only happen on day precision
* Turn off data checking for the first run of a package

feat: npm pagination

---

.github/workflows/os-observer-autocrawl.yml
.github/workflows/os-observer-manual.yml
os-observer/src/actions/autocrawl.ts
os-observer/src/cli.ts
os-observer/src/db/prisma-client.ts
os-observer/src/events/github.ts
os-observer/src/events/npm.ts
os-observer/src/utils/common.ts

* Update the manual fetcher GitHub action with new commands and ability to specify args
* Add a scheduled GitHub action to run autocrawl every day
* Add a FETCHER_REGISTRY for convenience
* Add a runAutocrawl CLI command that will iterate over EventSourcePointer table and run any marked for autocrawl
* Move normalizeToObject to common utilities

feat: enable scheduled autocrawl jobs

---

.github/workflows/deploy-os-observer.yml
.github/workflows/os-observer-autocrawl.yml
os-observer/package.json
package.json

* Add a deploy script to os-observer that just runs migrations
* Add a GitHub workflow that runs the migration on new migrations pushed to main
* Fix other os-observer workflows to correctly pipe the DATABASE_URL

feat: continuously deploy os-observer database migrations

---

frontend/components/zuzalu-hypercert-treemap.tsx
frontend/plasmic-init.ts

Had noticed I had a silly trailing comma in the included caption for the treemap. This makes it so you can embed your own children in the component but also that it can properly be formatted by plasmic.

Fixes formatting issues

---

frontend/components/hypercert-fetcher.tsx
frontend/lib/hypercert.test.ts
frontend/lib/hypercert.ts
frontend/lib/test-utils.ts
frontend/package.json
sdk/src/types/global.d.ts
sdk/src/types/index.ts
yarn.lock

Addresses #657 
Wanted to leave this draft up. Would have had this sooner but ran into some silly editor issues.
The proposed changes on this draft are a bit of a departure from what we might be doing in other parts of the code so I want to make sure people see it before I've finished everything. 
My thought was to organize this all in an object model that should hopefully become an intuitive interface for usage in plasmic. I don't remove direct access to the numeric values of the hypercert, but I am providing methods that I'd intend to be the main way to interface with data. 
So, for example: 
* To list all of the owners of a given hypercert do:`$ctx.hypercertData.listOwners()`. This will return objects that you could then use as a collection in plasmic.
* To get the ownership percentage …

Create different interface to Hypercert numeric values

---

yarn.lock

This is actually a problem. It seems the URL for the version on observablehq is not an immutable reference. So this will continue to break the build. Not yet sure the conditions for which things change - could just be updating the object on observerable or random. Would be worse if it's random.

Fix the fleek build

---

frontend/components/generic-hypercert-treemap.tsx
frontend/components/zuzalu-hypercert-treemap.compat.d.ts
frontend/plasmic-init.ts

Resolves #884 
Adds a new GenericHypercertTreemap. At this time, it doesn't handle background images. We need to fix #883 first.

Generic Treemap

---

frontend/components/generic-hypercert-treemap.tsx
frontend/plasmic-init.ts

My bad. Leaving some commented code in for a future self.

Fix builds after GenericHypercertsTreemap merge

---

frontend/components/generic-hypercert-treemap.tsx
frontend/plasmic-init.ts

This makes it so the component doesn't look broken when it is first dragged into the studio.

Improve generic hypercerts treemap ux

---

.lintstagedrc
cors-proxy/.eslintrc.json
cors-proxy/src/index.ts
defender/src/auto-tasks/batch-mint-claims-from-allowlists.ts
defender/src/auto-tasks/mint-claim-from-allowlist.ts
defender/src/auto-tasks/on-allowlist-created.ts
frontend/.eslintrc.json
frontend/.gitignore
frontend/components/dapp-context.tsx
frontend/components/dapp-state.tsx
frontend/package.json
package.json
yarn.lock

* Removed unused networks and put optimism network ahead of list
This is a workaround to get Safe to recognise that the app uses Optimism and will probably pop up again once we go multi-chain. 
--https://github.com/orgs/WalletConnect/discussions/2733
* Updated OZ Defender to skip unknown events in tx, since ethers fails on the Safe events in the TX:
-- https://github.com/ethers-io/ethers.js/issues/1233
-- https://optimistic.etherscan.io/tx/0x734e8f74d73de33a85adae65bd4ad06d6b68506b716427f8191c3976efb0ff2c#eventlog
* Need to merge to rollout defender updates.
* nohoist of wagmi + rainbowkit to solve build issues
* moved `eslintrc.yml` to package levels because of differences in ts versions, output dirs and others

fix(wc): updated wagmi networks and oz def handler

---

graph/src/utils.ts

* add mapping of allowlist to claim

fix(graph): update mapping to claim

---

.github/workflows/ci-default.yml
contracts/.solhint.json
contracts/remappings.txt
contracts/src/marketplace/LooksRareProtocol.sol
contracts/src/marketplace/TransferManager.sol
contracts/src/marketplace/TransferSelectorNFT.sol
contracts/src/marketplace/interfaces/ITransferManager.sol
contracts/src/protocol/AllowlistMinter.sol
contracts/src/protocol/HypercertMinter.sol
contracts/src/protocol/SemiFungible1155.sol
contracts/src/protocol/interfaces/IAllowlist.sol
contracts/src/protocol/interfaces/IHypercertToken.sol
contracts/test/foundry/marketplace/ProtocolBase.t.sol
contracts/test/foundry/marketplace/SignaturesERC1271WalletForHypercert.t.sol
contracts/test/foundry/marketplace/StandardTransactionsHypercerts.t.sol
contracts/test/foundry/marketplace/StrategyManager.t.sol
contracts/test/foundry/marketplace/TransferManager.t.sol
contracts/test/foundry/marketplace/utils/MockOrderGenerator.sol
contracts/test/mock/MockHypercertMinterUUPS.sol

* fix compiler linting warnings (for instance ^0.8.16 instead of 0.8.16)
* expand Transfer Manager tests with Hypercerts collection usecases
* add hypercertUUPS and hypercertMinter to ProtocolBase
* expand Signature tests for Hypercerts maker, taker, ask, bid, batch flows
* expand Standard Transactions tests with suite for Hypercerts
Implements:
#1109 
#1107 
#1111

Direct Hypercert fraction sale

---

frontend/components/hypercert-create.tsx
frontend/hooks/mintClaim.ts
frontend/hooks/mintClaimAllowlist.ts
frontend/plasmic-init.ts

Add transferRestrictions a parameter to mintClaim hooks in FE
Add transferRestrictions to hypercerts-create form in FE for plasmic
Add state prop for transferRestrictions to plasmic-init

feat(restriction): add transfer restriction to fe

---

frontend/components/hypercert-create.tsx
frontend/plasmic-init.ts

* Add minting application name to properties
* Add minting appliation name to Plasmic config

feat(metadata): add application name

---

contracts/audits/marketplace/2024_05_29_signature_bug.md
contracts/src/marketplace/ExecutionManager.sol
contracts/src/marketplace/LooksRareProtocol.sol
contracts/src/marketplace/TransferManager.sol
contracts/src/marketplace/TransferSelectorNFT.sol
contracts/src/marketplace/executionStrategies/StrategyHypercertCollectionOffer.sol
contracts/src/marketplace/executionStrategies/StrategyHypercertDutchAuction.sol
contracts/src/marketplace/executionStrategies/StrategyHypercertFractionOffer.sol
contracts/src/marketplace/helpers/OrderValidatorV2A.sol
contracts/src/marketplace/helpers/ProtocolHelpers.sol
contracts/src/marketplace/interfaces/IHypercert1155Token.sol
contracts/src/marketplace/libraries/LowLevelHypercertCaller.sol
contracts/test/foundry/marketplace/BatchMakerOrders.t.sol
contracts/test/foundry/marketplace/LooksRareProtocol.t.sol
contracts/test/foundry/marketplace/ProtocolBase.t.sol
contracts/test/foundry/marketplace/TransferManager.t.sol
contracts/test/foundry/marketplace/executionStrategies/HypercertCollectionOffers.t.sol
contracts/test/foundry/marketplace/executionStrategies/HypercertDutchAuctionOrders.t.sol
contracts/test/foundry/marketplace/executionStrategies/HypercertFractionOffers.t.sol

This PR covers the bug discussed in #1317 
When a user has set the approvals on the marketplace, an attacker could submit a transaction signed by the attacker for the (partial) sale of a hypercert fraction. The attacker would receive the funds, the order taker would receive the fraction and the fraction owner would lose a bit of the fraction.
To mitigate this, we added checks on the hypercert strategies where needed. Specifically, a check on ownership of the fraction by the signer of the message by calling the HyperMinter contract at time of order execution.
The vulnerability is specific to the split function call because there is not check there on the operator-msg.sender relations/approval as common in the transferFrom methods. This is an artifact from changing the original design where …

Bugfix in signature validations marketplace
