README.md
frontend/README.md

Trying to get in the habit of small commits in separate PRs so people can comment

fix(docs): Quick README on how to get going on the frontend

---

frontend/components/forms.tsx
frontend/components/hypercert-create.tsx
frontend/package.json
frontend/plasmic-init.ts
frontend/yarn.lock

* Updated DatePicker component to include an optional checkbox that sets it as undefined (e.g. for infinite work end date)
* Added a Dropzone component
* Updated create hypercert UI to latest designs

feat(design): Implementing new designs

---

README.md

Wanted a place to track where we've deployed this app so far and links to resources so people can find related repos.

docs(README): Added links to current resources on README

---

frontend/components/forms.tsx
frontend/components/hypercert-create.tsx
frontend/plasmic-init.ts

* Add a "agree to terms and conditions" checkbox
* Added FormCheckbox as a Plasmic code component
* Update validation logic for new form field types
* Selects can be disabled
*

feat(create): Update creation form to latest designs

---

frontend/components/hypercert-create.tsx

fix(create): Don't let the create form URL convey agreement

---

frontend/components/hypercert-create.tsx

* passing in a backgroundColor=teal or purple or green will render the right background color in the image0

feat(image): specify a backgroundColor via querystring

---

frontend/components/hypercert-create.tsx
frontend/package.json
yarn.lock

* using html2canvas for image capture
* Disabling submit button while submitting

feat(image): convert HypercertImage preview into a data URL

---

frontend/components/supabase-query.tsx
frontend/plasmic-init.ts

* Allows us to specify unauthenticated Supabase queries in Plasmic

feat: Add a generic SupabaseQuery component

---

frontend/components/hypercert-fetcher.tsx
frontend/components/supabase-query.tsx
frontend/plasmic-init.ts

* Specify providesData for the SupabaseQuery, which was missing
* add a `useQueryString` prop for HypercertFetcher, which specifies order of preference

fix: Plasmic code components for fetching

---

.github/workflows/ci-default.yml
package.json

feat: basic CI via GitHub Actions

---

.github/workflows/ci-default.yml
README.md

* Add GitHub Actions status badge on README
* Fix CI to run `yarn install`
* Fix CI to run off `main`

fix: Fix issues with GitHub Actions

---

frontend/components/hypercert-create.tsx
frontend/hooks/mintClaim.ts
frontend/hooks/mintClaimAllowlist.ts
frontend/hooks/mintFractionAllowlist.ts
frontend/hooks/mintFractionAllowlistBatch.ts

* From eslint warnings, I added deps to the useEffect that weren't there before. I think this is causing an infinite loop

fix: revert changes from linting mint hooks

---

cors-proxy/package.json
cors-proxy/src/index.test.ts
cors-proxy/src/index.ts
cors-proxy/tsconfig.json
cors-proxy/wrangler.toml
package.json
yarn.lock

* This is a lightweight version of the demo from https://developers.cloudflare.com/workers/examples/cors-header-proxy
* Currently allows any origin, hopefully not a huge issue

feat: CORS proxy for Cloudflare workers

---

.github/workflows/ci-default.yml
.gitignore
cors-proxy/package.json

* Updated GitHub actions workflow to also do a build
* Update cors-proxy testing to be one-shot, not watch mode

fix: Updated GitHub actions workflow to also do a build

---

README.md
frontend/hooks/mintClaim.ts
frontend/hooks/mintClaimAllowlist.ts

* Should be FromCreatorOnly for both mintClaim and mintClaimAllowlist
* The ordering/numbering of the enum was wrong!
* Updated README with new directory structure

fix: fixing hardcoded transferRestriction in frontend

---

frontend/components/hypercert-create.tsx

* Using our CORS proxy
* Removed some string validation

fix: only use CORS proxy when user clicks submit

---

frontend/components/hypercert-create.tsx

* To use, pass in a `metadataProperties` value into the query string of the create form with a stringified JSON value that matches what we expect in the properties field.
* If the value does not pass validation, it'll cause the form to fail.

feat: Allow `metadataProperties` to be passed into create URL

---

docs/docs/glossary.md

chore(docs): review glossary

---

docs/docs/glossary.md

Reviewed the following terms:
A token that (1) accounts for work by specified contributors that is supposed to be impactful, (2) represents the – potentially explicitly specified – impact of this work, and (3) assigns right over this work to its owners. If a hypercert is split into multiple fractions, the hypercert refers to the sum of all of its fractions. Hypercert also refers to the hypercert standard that defines the token and data standard for hypercerts.
An implementation that builds on top of the [hypercerts interface](https://github.com/hypercerts-org/hypercerts/blob/main/contracts/src/interfaces/IHypercertToken.sol) and conforms to the hypercerts standard. For instance, our initial implementation uses an [ERC-1155](https://eips.ethereum.org/EIPS/eip-1155) token. The first 128 …

docs: incorporated feedback from bitbecker; separated IE terms

---

package.json

* Configuring our page host to just run `yarn build:site`

fix: separate build script for just the web app

---

.github/workflows/deploy-graph.yml
README.md
package.json

* typo in build script
* Only deploy subgraph if files change in the graph/ directory

fix: subgraph deployment

---

.github/workflows/deploy-defender.yml
README.md
defender/package.json
defender/src/config.ts
package.json

* Added a GitHub action to deploy changes to the defender scripts
* Updated README references to GitHub actions
* Updated defender package.json

feat: continuous deploy defender tasks

---

contracts/src/AllowlistMinter.sol

feat(gap): added storage gap AllowlistMinter

---

docs/docs/devops/plasmic.md
frontend/components/hypercert-fetcher.tsx
frontend/lib/verify-fraction-claim.ts

* Fixed some references that were previously using getData and getMetadata directly
* Added a Plasmic config doc for upgrading the HypercertImage component

fix: use HypercertsStorage in frontend

---

defender/src/auto-tasks/on-allowlist-created.ts
frontend/hooks/mintClaim.ts
frontend/hooks/mintClaimAllowlist.ts
frontend/lib/formatting.ts
frontend/package.json
yarn.lock

* For both metadataUri and allowlistUri, we should be prefixing the CID with ipfs://

fix: prefix CIDs with ipfs:// for URIs

---

frontend/package.json
yarn.lock

fix: upgrade plasmic dependency

---

frontend/components/hypercert-create.tsx
frontend/package.json
sdk/docs/RELEASE.md
sdk/package.json
sdk/src/formatter.ts
sdk/src/minting.ts
sdk/src/resources/schema/claimdata.json
sdk/test/formatter.test.ts
yarn.lock

* format 0 dates as "indefinite"
* fix off-by-one error in the date
* use UTC variant of getDate, getMonth, getFullYear
* Fix wrong ordering of TransferRestrictions
* Add descriptions to claimdata schema
* Add tests for date formatting

fix: formatting dates in the SDK

---

frontend/components/config.tsx
frontend/components/dapp-context.tsx
frontend/components/hypercert-create.tsx
frontend/lib/config.ts

* Adds a toast if you try to create but you're on the wrong network

fix: show error message if on wrong network

---

frontend/lib/errors.ts
frontend/lib/parsing.test.ts
frontend/lib/parsing.ts

* Added a condition to check if the total supply turns out to be 0.

fix: empty allowlists should throw an exception

---

frontend/.gitignore
frontend/next.config.js
frontend/package.json
frontend/pages/_error.js
frontend/pages/sentry_sample_error.js
frontend/sentry.client.config.js
frontend/sentry.edge.config.js
frontend/sentry.properties
frontend/sentry.server.config.js
yarn.lock

* Setup the frontend with Sentry
* Note: This does not current discriminate between dev, staging, testnet, production, mainnet etc.

feat: Add Sentry integration

---

README.md
docs/docs/developer/index.md
docs/docs/developer/quickstart-javascript.md
docs/docs/developer/quickstart-solidity.md
docs/docs/devops/deploy-proxy.md
docs/docs/devops/errors.md
docs/docs/devops/index.md
docs/docs/devops/pause.md
docs/docs/devops/plasmic.md
docs/docs/devops/setup.md
docs/docs/devops/unpause.md
docs/docs/devops/upgrade.md

* Write up a strawman SDK interface proposal
* Fix headings for devops guide
* Fix badge link in README

docs: add a SDK interface proposal

---

frontend/package.json
frontend/plasmic-init.ts
yarn.lock

* Add some helper text around code component props for ease of use
* Updated loader-nextjs dependency

fix: Plasmic code component help text

---

.github/workflows/ci-default.yml

* Trying to fix uploads of source maps

fix: adding SENTRY_AUTH_TOKEN to environment for CI/CD

---

frontend/components/widgets.tsx
frontend/plasmic-init.ts

* Give Plasmic users ability to set fontSize, fontColor, and backgroundColor

fix: Add tooltip styling

---

frontend/components/hypercert-fetcher.tsx
frontend/components/supabase-query.tsx
frontend/plasmic-init.ts

* Allow Plasmic users to specify what to show when still loading
* Add custom variable names for SupabaseQuery and HypercertFetcher

feat: Expose loading state to SupabaseQuery

---

frontend/components/forms.tsx
frontend/plasmic-init.ts

* Adding a basic Formik-wrapped slider component

feat: slider component for Plasmic

---

frontend/components/forms.tsx
frontend/components/hypercert-create.tsx
frontend/hooks/mintClaimAllowlist.ts
frontend/plasmic-init.ts

* Added `allowlistPercentage` for how much is distributed via allowlist
* Updated logic to remove hardcoded 50% and use the form data
* Enabled `disabled` for slider and textfields

feat: let a user configure what fraction they keep from allowlist

---

frontend/lib/verify-fraction-claim.ts

* Addresses this bug https://github.com/hypercerts-org/hypercerts/issues/601

fix: fixing claim all fractions

---

sdk/src/config.ts
sdk/src/operator/hypercerts-storage.ts
sdk/src/utils/errors.ts

* winston ConsoleTransport doesn't work in browsers
* restoring using console.log for now

fix: removing uses of logger

---

frontend/components/hypercert-create.tsx
frontend/hooks/hypercerts-client.ts
frontend/hooks/mintClaimSDK.ts
sdk/src/client.ts
sdk/src/index.ts
sdk/src/types/client.ts
sdk/test/operator/hypercerts-minting.test.ts

* Use mint function from SDK in FE app
* Export Provider instead of BaseProvider from SDK
* Add export of TransactionRestrictions to SDK
Closes #303

303 sdk mint functions not exported

---

frontend/package.json
yarn.lock

* Updated wagmi and rainbowkit to 0.12.12

fix(wagmi): update wagmi version

---

frontend/components/supabase-query.tsx
frontend/components/supabase-to-chart.tsx
frontend/plasmic-init.ts

* Registering SupabaseToChart, which fetches from supabase in a way that works well for charting. This is WIP, but worth committing so that we have a placeholder in the Plasmic project while debugging the Supabase query
* Fixed useEffect dependencies in SupabaseQuery

feat: supabase-to-chart WIP

---

frontend/hooks/burnFraction.ts
sdk/test/client/burn.test.ts

* Added SDK tests for burn method
* Added burn hook to FE
Implements #82

Burn a hypercert

---

frontend/hooks/claims.ts
sdk/.graphclient/index.ts
sdk/.graphclientrc.yml
sdk/src/index.ts
sdk/src/queries/claims.graphql
sdk/src/queries/claims.ts
sdk/src/queries/fractions.graphql
sdk/src/queries/fractions.ts
sdk/src/queries/utils.ts

* Added params object to graph in SDK
* Default params in queries
* Updated app to use defaults (ie no input)
Closes #548

548 sdk open up graph queries

---

frontend/components/hypercert-create.tsx

* check balance in create form
* throw error on no balance found
Closes #460

feat(balance): reject tx on no balance

---

CONTRIBUTING.md
frontend/_redirects
package.json

* Also adding a _redirects file, for setting up redirects with Cloudflare. https://developers.cloudflare.com/pages/platform/redirects
NOTE: every CDN has their own redirect conventions. This will not work on Vercel or Fleek

docs: adding CONTRIBUTING.md

---

frontend/components/claim-all-fractions-button.tsx
frontend/components/hypercert-create.tsx

* added to create form
* added to claim all button
Closes #673

460 error message when minter or claimer has no eth

---

frontend/components/zuzalu-purchase.tsx
frontend/plasmic-init.ts
graph/generated/schema.ts

* Adds the Zuzalu purchase form with validation logic to check for valid percentages
* Note: this dpes not yet initiate a transfer transaction
* This autogenerates some docs that were missing previously

feat: Add Zuzalu purchase form code component

---

frontend/components/zuzalu-purchase.tsx

* Adds fields for all 22 hypercerts
* Adds conversion from percentage => USD => ETH => wei
* Adds logic to log to supabase
* Adds sendTransaction

feat: zuzalu MVP

---

frontend/components/zuzalu-purchase.tsx

* a 23rd hypercerts
* an arbitrary text field

feat: Zuzalu form adding new fields

---

sdk/src/client.ts
sdk/test/client/burn.test.ts
sdk/test/client/minting.test.ts
sdk/test/client/split.merge.test.ts

* Add overrides to SDK tx methods
* Add testing to client evm methods

Add overrides to SDK evm methods

---

os-observer/prisma/migrations/20230601011521_add_contributors/migration.sql
os-observer/prisma/schema.prisma

* Generated a migration to do this
* Added a unique constraint to organization githubOrg

feat: Add Contributor table to prisma schema

---

os-observer/README.md
os-observer/package.json
os-observer/supabase/.gitignore
os-observer/supabase/config.toml
yarn.lock

* Added the supabase dependency to be able to run a local developer instance
* Included better instructions in the README on how to get started

feat: local supabase instance

---

os-observer/src/events/npm.ts

* Quick fix of subtracting 2 days from today to see what happens

fix: npm downloads seems to be fetching up to today

---

frontend/components/tableau-view.tsx
frontend/plasmic-init.ts

* Just a shell component right now to be able to play around with the Embedding API

feat: tableau component

---

frontend/components/zuzalu-hypercert-treemap.compat.d.ts
frontend/components/zuzalu-hypercert-treemap.tsx
frontend/package.json
yarn.lock

Add treemap to components

---

frontend/plasmic-init.ts

My bad... didn't register the component.

Register ZuzaluHypercertTreemap component

---

frontend/package.json
yarn.lock

I realized this won't be a long term fix still. I'm going to introduce a fix after this. I'll merge so builds keep working.

Use immutable observablehq package

---

vendor/observabletreemap/c857fa5c110524ee@515.js
vendor/observabletreemap/files/af40c6fdb79581388488f364d8ef0bab6388ba6c45ccae8b8e691939048c2de72f421898ecbe772c1ed529a8c75acc2cf02ec1ab6d3d53014273688cfffaef6c.json

update of the data and disabling the background image as it doesn't function as expected yet

Update zuzualu billboard

---

docs/docusaurus.config.js
docs/package.json
yarn.lock

* Fixes the mermaid theme colors in dark mode
* Updating docusaurus to 2.4.1

fix: docusaurus mermaid theme colors

---

frontend/package.json
yarn.lock

chore(update): wagmi + rainbowkit updates

---

frontend/components/zuzalu-purchase.tsx
frontend/hooks/checkWriteable.ts

* Added check hooks to Zuzalu form because it uses a different chain (mainnet)
* Wrapped hooks in onSubmit and use formik callback

fix(form): added checks and submit hook

---

frontend/components/project-browser/css/browser.module.css
frontend/components/project-browser/css/data-table.module.css
frontend/components/project-browser/data-table/field-default.tsx
frontend/components/project-browser/data-table/field-growth.tsx
frontend/components/project-browser/data-table/field-label.tsx
frontend/components/project-browser/data-table/field-project.tsx
frontend/components/project-browser/data-table/field-status.tsx
frontend/components/project-browser/project-browser.tsx
frontend/components/project-browser/project-client-provider.tsx
frontend/components/project-browser/project-contexts.tsx
frontend/components/project-browser/project-data-table.tsx
frontend/lib/data-table.tsx
frontend/lib/projects.tsx
frontend/package.json
frontend/plasmic-init.ts
yarn.lock

Getting this merged in so I can actually just style on plasmic a little easier. I'll add it to the official os observer as opposed to my local test project. I'm merging this right now. PR is a formality.

OS Observer UI

---

defender/src/auto-tasks/batch-mint-claims-from-allowlists.ts
defender/src/auto-tasks/mint-claim-from-allowlist.ts
defender/src/auto-tasks/on-allowlist-created.ts

* Added null check to db response to make sure we throw when the db response is empty

fix(oz): check on db result

---

defender/src/networks.ts
yarn.lock

* updates name to match current supabase state

fix(db): updated table names in defender

---

frontend/package.json
graph/generated/schema.ts
graph/package.json
sdk/RELEASE.md
sdk/package.json
yarn.lock

* update web3.storage and nft.storage
* update dependencies graph package

chore(update): update deps graph and sdk

---

frontend/hooks/mintFractionAllowlistBatch.ts

* Update query to filter on hidden column
Closes #1056

feat(db): update allowlist query

---

contracts/.openzeppelin/goerli.json
contracts/src/HypercertTrader.sol
contracts/test/foundry/HypercertTrader.admin.t.sol
contracts/test/foundry/HypercertTrader.offers.t.sol
contracts/test/foundry/HypercertTrader.sales.t.sol
docs/docs/developer/api/contracts/HypercertTrader.md
graph/abis/HypercertTrader.json
graph/generated/HypercertTrader/HypercertTrader.ts
graph/generated/schema.ts
graph/package.json
graph/schema.graphql
graph/src/utils.ts
graph/tests/hypercert-trader.test.ts

* Add getter method for Offer struct to contract and update
* Updated Graph with entities for accepted tokens and mappings

feat(tokens): surface accepted tokens

---

.github/workflows/deploy-graph.yml

* Use pnpm cache instead of yarn in GHA

fix(gha): use pnpm cache in graph gha

---

contracts/hardhat.config.ts
contracts/package.json
contracts/src/index.ts
contracts/test/foundry/marketplace/LooksRareProtocol.t.sol

* Release contract alpha.7
* Add step for currency admin flow in looksRare test suite

fix(test): add currency admin to test

---

frontend/package.json
pnpm-lock.yaml

* web3 connector deps bump in fe following ledgerconnect hack

chore(bump): web3 connectors fe

---

sdk/RELEASE.md
sdk/package.json
sdk/src/client.ts
sdk/src/storage.ts
sdk/src/types/client.ts
sdk/src/utils/apis.ts
sdk/src/utils/fetchers.ts

* Unopiniated timouts; default to 0
* Expose axios timout var from storage level up to utils and client methods

fix(http): unopiniated timeouts on calls. 1.4.2-alpha.1

---

defender/src/setup.ts
graph/networks.json

* base and base sepolia address and startBlock in graph network config

fix(graph): addresses and startBlocks

---

frontend/hooks/verifyFractionClaim.ts

Hotfix for allowlist comparison

fix(lowercase): compare addresses lowercased
